# fly.toml app configuration file generated for idp-admin on 2024-04-04T16:34:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'idp-admin'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
